### PR TITLE
SYN-04: Feature/GUI

### PR DESCRIPTION
**Pull request by FilipZiva**
### Feature Ticket: SYN-04: GUI

# Overview
This JavaFX application is a slot machine game developed in Java, utilizing the JavaFX framework for its graphical user interface.

## Key Features
- **Spin Functionality:** Triggered by the `spinBtn`, this initiates the slot machine's reels, generating a random set of symbols upon each use.
- **Bet Adjustment:** The `increaseBetBtn` and `decreaseBetBtn` allow the player to modify their bet amount before each spin.
- **Symbol Information:** An `infoBtn` provides details about the symbols and game rules. -> To Do 
- **Symbol Display:** `symbol1` to `symbol5` ImageView elements showcase the results of each spin.
- **Balance and Bet Display:** `balanceLabel` and `betLabel` dynamically display the player's current balance and bet amount.

## Gameplay Logic
The `GameManager` class manages the core gameplay, including generating spin results and calculating winnings. After each spin, it updates the symbols displayed and the player's new balance.

## User Interface
The application features a user-friendly and visually appealing interface. The layout and graphics for the UI are defined in an FXML file, while the `SlotMachineController` class handles user interactions and behaviors.

### CODE REVIEW

**Review by swaglord21 — APPROVED** [review]
very good work guys! keep up the grind

**Review by DavidLisnjicS — APPROVED** [review]
Really clean and well put together Code. The finall "product" is behind the corner.

**Comment by cjserrano112** [comment]
Looks very good, really nice job!

**Review by cjserrano112 — APPROVED** [review]
Looks good.

**Review by Camono — APPROVED** [review]
ok

**Pull request merged**
